// <auto-generated />
namespace BTC_R.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Verification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Verification));
        
        string IMigrationMetadata.Id
        {
            get { return "201706051222502_Verification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
